# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('close_date', models.DateTimeField(verbose_name='Close Date')),
                ('open_price', models.IntegerField(default=0)),
                ('close_price', models.IntegerField(default=0)),
                ('avg_price', models.IntegerField(default=0)),
                ('floor_price', models.IntegerField(default=0)),
                ('ceiling_price', models.IntegerField(default=0)),
                ('highest', models.IntegerField(default=0)),
                ('lowest', models.IntegerField(default=0)),
                ('oscillate', models.IntegerField(default=0)),
                ('dividend', models.IntegerField(default=0)),
                ('eps', models.IntegerField(default=0)),
                ('buy_redundancy', models.IntegerField(default=0)),
                ('sell_redundancy', models.IntegerField(default=0)),
                ('bvps', models.IntegerField(default=0)),
                ('capital_level', models.IntegerField(default=0)),
                ('curr_room', models.IntegerField(default=0)),
                ('klcplh', models.BigIntegerField(default=0)),
                ('klcpny', models.BigIntegerField(default=0)),
                ('avg_vol', models.IntegerField(default=0)),
                ('trading_vol', models.BigIntegerField(default=0)),
                ('total_vol', models.BigIntegerField(default=0)),
                ('beta', models.DecimalField(decimal_places=5, max_digits=10)),
                ('dec_pb', models.DecimalField(decimal_places=10, max_digits=20)),
                ('dec_pe', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fw_pe', models.DecimalField(decimal_places=10, max_digits=20)),
                ('raw_json', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=5)),
                ('url', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='StockIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='listed_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.StockIndex'),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.Stock'),
        ),
    ]
