# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_errorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='dest_url',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
