# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_errorlog_dest_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.IntegerField(default=0)),
                ('data', models.BinaryField()),
                ('date', models.DateTimeField()),
                ('accuracy', models.DecimalField(decimal_places=8, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='close_date',
            field=models.DateTimeField(db_index=True, verbose_name='Close Date'),
        ),
    ]
