# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_auto_20170309_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LearnModels',
            new_name='LearnModel',
        ),
    ]
