# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 04:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20170309_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scaler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('data', models.BinaryField()),
            ],
        ),
        migrations.AddField(
            model_name='learnmodel',
            name='scaler',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='stocks.Scaler'),
            preserve_default=False,
        ),
    ]
