# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_auto_20170310_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learnmodel',
            name='data',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scaler',
            name='data',
            field=models.CharField(max_length=255),
        ),
    ]
