# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 04:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_auto_20170310_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
