# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_stock_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='industry',
            field=models.IntegerField(default=0),
        ),
    ]
