# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_auto_20170315_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calibrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('data', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='learnmodel',
            name='calibrator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stocks.Calibrator', null=True),
            preserve_default=False,
        ),
    ]
